FROM python:3.10-slim-bullseye


RUN mkdir - p /home/questionnaireProject
WORKDIR /home/questionnaireProject

COPY ./requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt


CMD ["gunicorn", "-b", "0.0.0.0:8000", "questionnaireProject.wsgi:application"]

EXPOSE 8000