# Generated by Django 4.2.11 on 2024-05-07 12:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.TextField(verbose_name='Название опроса')),
                ('quiz_title_subtitle', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация об опросе')),
                ('quiz_title_date_create', models.DateField(default=datetime.date.today, verbose_name='Дата создания опроса')),
                ('quiz_title_status', models.BooleanField(default=True, verbose_name='Статус опроса: (Завершён/Незавршён)')),
                ('quiz_title_url', models.TextField(default='1c4aa378a0f84848738afa3dbbae24e9', verbose_name='url идентификатор по кторому доступен тест')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_title', models.TextField(verbose_name='Текст вопроса')),
                ('q_one_answer', models.BooleanField(default=True, verbose_name='Один ответ')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaireApp.quiz', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Choise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_title', models.TextField(verbose_name='Содержание выбора ответа')),
                ('ch_points', models.IntegerField(default=0, verbose_name='Баллы за ответ, если опрос для статистики, то балл 0')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaireApp.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_token', models.TextField(verbose_name='токен пользователя')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('choise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaireApp.choise', verbose_name='Выбранный вариант ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaireApp.question', verbose_name='Вопрос на который отвечает пользователь')),
            ],
            options={
                'verbose_name': 'Ответы пользователей',
            },
        ),
    ]
