# Generated by Django 4.2.11 on 2024-05-07 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaireApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ пользователя', 'verbose_name_plural': 'Ответы пользователей'},
        ),
        migrations.RemoveField(
            model_name='choise',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AddField(
            model_name='answer',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questionnaireApp.quiz', verbose_name='Опрос в котором участвует пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='q_choises',
            field=models.ManyToManyField(blank=True, to='questionnaireApp.choise', verbose_name='Варианты ответов'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, to='questionnaireApp.question', verbose_name='Вопросы опроса'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_token',
            field=models.TextField(verbose_name='Токен пользователя'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_title_url',
            field=models.TextField(default='03cf914849c9182aa8585bd1c543b830', verbose_name='url идентификатор по кторому доступен тест'),
        ),
    ]
